groups:
- name: service-discovery
  jobs:
  - unit-tests
  - acceptance-tests
  - smoke-tests
  - ushanka-deploy
- name: ushanka
  jobs:
  - ushanka-bbl-up
  - ushanka-bbl-destroy
  - ushanka-deploy
- name: beret
  jobs:
  - beret-bbl-up
  - beret-bbl-destroy

resources:
  - name: service-discovery-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/service-discovery-release
  - name: cf-deployment-concourse-tasks
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
      branch: master
  - name: cf-networking-deployments
    type: git
    source:
      uri: "git@github.com:cloudfoundry/cf-networking-deployments.git"
      branch: master
      private_key: {{cf-networking-deployments-push-key}}
  - name: cf-deployment
    type: git
    source:
      branch: release-candidate
      uri: https://github.com/cloudfoundry/cf-deployment.git
  - name: cf-networking-dev
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-networking-release.git
      branch: develop
      ignore_paths:
        - docs
      private_key: {{cf-networking-deploy-key}}
  ####### Timers
  - name: every-fifteen-minutes
    type: time
    source:
      interval: 15m

jobs:
  - name: unit-tests
    plan:
      - aggregate:
          - get: service-discovery-release
            trigger: true
      - task: unit-tests
        file: service-discovery-release/ci/tasks/test-unit.yml

  - name: acceptance-tests
    serial_groups: [ushanka-deploy-group, ushanka-test-group]
    plan:
      - aggregate:
          - get: cf-networking-deployments
          - get: service-discovery-release
            passed: [ushanka-deploy]
            trigger: true
      - task: acceptance-tests
        privileged: true
        file: service-discovery-release/ci/tasks/test-acceptance.yml
        input_mapping:
          test-config: cf-networking-deployments
          vars-store: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: ushanka

  - name: smoke-tests
    serial_groups: [ushanka-test-group]
    plan:
      - aggregate:
          - get: every-fifteen-minutes
            trigger: true
          - get: cf-networking-deployments
          - get: service-discovery-release
            passed: [ushanka-deploy]
            trigger: true
      - task: smoke-tests
        privileged: true
        file: service-discovery-release/ci/tasks/smoke-tests.yml
        input_mapping:
          test-config: cf-networking-deployments
        params:
          ENVIRONMENT_NAME: ushanka
          ENVIRONMENT_TAG: ushanka.c2c.cf-app.com
          DATADOG_API_KEY: {{datadog_api_key}}

  - name: ushanka-bbl-up
    serial_groups: [ushanka-deploy-group, ushanka-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-up
        file: cf-deployment-concourse-tasks/bbl-up/task.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: ../gcp/service-account.key.json
          BBL_GCP_PROJECT_ID: cf-container-networking-gcp
          BBL_GCP_REGION: us-east1
          BBL_GCP_ZONE: us-east1-b
          BBL_STATE_DIR: environments/ushanka/
          BBL_IAAS: gcp
          BBL_LB_CERT: {{ushanka-lb-cert}}
          BBL_LB_KEY: {{ushanka-lb-key}}
          LB_DOMAIN: ushanka.c2c.cf-app.com
          BBL_ENV_NAME: ushanka
          OPS_FILES: local-dns.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          ops-files: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true

  - name: ushanka-bbl-destroy
    serial_groups: [ushanka-deploy-group, ushanka-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
        input_mapping:
          bbl-state: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true

  - name: ushanka-deploy
    serial_groups: [ushanka-deploy-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
          - get: cf-deployment
            trigger: true
          - get: cf-networking-dev
          - get: service-discovery-release
            trigger: true
            passed: [unit-tests]
      - task: upload-stemcell
        file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
        input_mapping:
          bbl-state: cf-networking-deployments
      - task: collect-ops-files
        file: service-discovery-release/ci/tasks/collect-ops-files.yml
        params:
          ENVIRONMENT_NAME: ushanka
        input_mapping:
          cf-networking-release: cf-networking-dev
          deployments-repo: cf-networking-deployments
      - task: upload-local-service-discovery-releases
        file: service-discovery-release/ci/tasks/upload-local-release.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          local-release: service-discovery-release
        params:
          BBL_STATE_DIR: environments/ushanka/
      - task: deploy-cf
        file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
          SYSTEM_DOMAIN: ushanka.c2c.cf-app.com
          OPS_FILES: use-compiled-releases.yml datadog.yml cf-networking.yml use-bosh-dns-for-containers.yml opsfile.yml
          VARS_STORE_FILE: environments/ushanka/vars-store.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          release: cf-networking-dev
          vars-files: cf-networking-deployments
          vars-store: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-vars-store
            rebase: true
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
          CLEAN_ALL: false
        input_mapping:
          bbl-state: cf-networking-deployments

  - name: beret-bbl-up
    # serial_groups: [beret-deploy-group, beret-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-up
        file: cf-deployment-concourse-tasks/bbl-up/task.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: ../gcp/service-account.key.json
          BBL_GCP_PROJECT_ID: cf-container-networking-gcp
          BBL_GCP_REGION: us-east1
          BBL_GCP_ZONE: us-east1-b
          BBL_STATE_DIR: environments/beret/
          BBL_IAAS: gcp
          BBL_LB_CERT: {{beret-lb-cert}}
          BBL_LB_KEY: {{beret-lb-key}}
          LB_DOMAIN: beret.c2c.cf-app.com
          BBL_ENV_NAME: beret
          OPS_FILES: local-dns.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          ops-files: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true

  - name: beret-bbl-destroy
    # serial_groups: [ushanka-deploy-group, ushanka-test-group]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: environments/beret/
        input_mapping:
          bbl-state: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true
