---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: cf-app-sd-release
  - name: cf-deployment
  - name: deployments-repo

outputs:
  - name: ops-files

run:
  path: cf-app-sd-release/ci/tasks/collect-ops-files

params:
  ENVIRONMENT_NAME: ~
