---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
- name: cf-app-sd
- name: version
- name: cf-app-sd-ci

outputs:
- name: tarballs

run:
  path: cf-app-sd-ci/ci/tasks/create-release-tarball

params:
  RELEASE_NAME: cf-app-sd
