---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: service-discovery-ci
  - name: cf-networking-deployments
  - name: service-discovery-tarball
  - name: service-discovery

outputs:
  - name: final-release
  - name: release

run:
  path: service-discovery-ci/ci/tasks/ship-it
