---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: service-discovery-release
  - name: test-config

params:
    ENVIRONMENT_NAME: ~
    ENVIRONMENT_TAG: ~
    CONFIG: ~
    DATADOG_API_KEY: ~

run:
  path: service-discovery-release/ci/tasks/service-discovery/smoke-tests
