---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.9'

inputs:
  - name: cf-app-sd-release

params: {}

run:
  path: cf-app-sd-release/ci/tasks/test-unit
