---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy-light

inputs:
  - name: service-discovery-release
  - name: deployments-repo

params:
  ENVIRONMENT_NAME: ~

run:
  path: service-discovery-release/ci/tasks/test-nats-performance
