---
name: performance

addons:
- include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    properties:
      aliases:
        _.cell.service.cf.internal:
        - _.diego-cell.default.cf.bosh
        - _.windows-cell.default.cf.bosh
        - _.windows2016-cell.default.cf.bosh
        - _.isolated-diego-cell.default.cf.bosh
        auctioneer.service.cf.internal:
        - "*.scheduler.default.cf.bosh"
        bbs.service.cf.internal:
        - "*.diego-api.default.cf.bosh"
        blobstore.service.cf.internal:
        - "*.blobstore.default.cf.bosh"
        - "*.singleton-blobstore.default.cf.bosh"
        cc-uploader.service.cf.internal:
        - "*.api.default.cf.bosh"
        cf-etcd.service.cf.internal:
        - "*.etcd.default.cf.bosh"
        cloud-controller-ng.service.cf.internal:
        - "*.api.default.cf.bosh"
        consul.service.cf.internal:
        - "*.consul.default.cf.bosh"
        credhub.service.cf.internal:
        - "*.credhub.default.cf.bosh"
        doppler.service.cf.internal:
        - "*.doppler.default.cf.bosh"
        file-server.service.cf.internal:
        - "*.api.default.cf.bosh"
        gorouter.service.cf.internal:
        - "*.router.default.cf.bosh"
        locket.service.cf.internal:
        - "*.diego-api.default.cf.bosh"
        loggregator-trafficcontroller.service.cf.internal:
        - "*.log-api.default.cf.bosh"
        nsync.service.cf.internal:
        - "*.scheduler.default.cf.bosh"
        policy-server.service.cf.internal:
        - "*.api.default.cf.bosh"
        reverse-log-proxy.service.cf.internal:
        - "*.log-api.default.cf.bosh"
        routing-api.service.cf.internal:
        - "*.api.default.cf.bosh"
        service-discovery-controller.internal:
        - _.diego-cell.default.cf.bosh
        silk-controller.service.cf.internal:
        - "*.diego-api.default.cf.bosh"
        sql-db.service.cf.internal:
        - "*.mysql.default.cf.bosh"
        - "*.postgres.default.cf.bosh"
        - "*.singleton-database.default.cf.bosh"
        ssh-proxy.service.cf.internal:
        - "*.scheduler.default.cf.bosh"
        stager.service.cf.internal:
        - "*.api.default.cf.bosh"
        tcp-router.service.cf.internal:
        - "*.tcp-router.default.cf.bosh"
        tps.service.cf.internal:
        - "*.scheduler.default.cf.bosh"
        uaa.service.cf.internal:
        - "*.uaa.default.cf.bosh"
      handlers:
      - domain: sd-local.
        source:
          type: http
          url: http://127.0.0.1:8053
    release: bosh-dns
  name: bosh-dns

instance_groups:
- azs:
  - z1
  - z2
  instances: 1
  jobs:
  - name: performance-tests
    properties: {}
    release: service-discovery
  lifecycle: errand
  name: performance-tests
  networks:
  - name: private
  stemcell: default
  vm_type: m3.medium

- azs:
  - z1
  - z2
  instances: 1

  jobs:
  - name: nats
    properties:
      nats:
        debug: true
        monitor_port: 8222
        password: ((nats_password))
        trace: true
        user: nats
    provides:
      nats:
        as: nats
        shared: true
    release: nats
  name: nats
  networks:
  - name: default
    static_ips: [((nats_ip))]
  stemcell: default
  vm_type: minimal

- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: bosh-dns-adapter
    properties:
      dnshttps:
        client:
          tls:
            ca: ((service_discovery_ca.ca))
            certificate: ((service_discovery_client_tls.certificate))
            private_key: ((service_discovery_client_tls.private_key))
        server:
          ca: ((service_discovery_ca.ca))
    release: service-discovery
  - name: service-discovery-controller
    properties:
      dnshttps:
        client:
          ca: ((service_discovery_ca.ca))
        server:
          tls:
            ca: ((service_discovery_ca.ca))
            certificate: ((service_discovery_server_tls.certificate))
            private_key: ((service_discovery_server_tls.private_key))
    release: service-discovery
  name: service-discovery
  networks:
  - name: default
  stemcell: default
  update:
    max_in_flight: 20
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: small-highmem

releases:
- name: nats
  sha1: bdb04d0d18a71d8b3144e477c43c0f5c72c2eccb
  stemcell:
    os: ubuntu-trusty
    version: '3468'
  url: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-22-ubuntu-trusty-3468-20171006-173847-874271262.tgz
  version: '22'
- name: bosh-dns
  sha1: daa521930560a5f8543823b2a2984131561362c5
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.0.10
  version: 0.0.10
- name: service-discovery
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3468'
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000
variables:
- name: nats_password
  type: password
- name: service_discovery_ca
  type: certificate
  options:
    is_ca: true
    common_name: service-discovery-controller.internal
- name: service_discovery_server_tls
  type: certificate
  options:
    ca: service_discovery_ca
    common_name: service-discovery-controller.internal
    extended_key_usage:
    - server_auth
- name: service_discovery_client_tls
  type: certificate
  options:
    ca: service_discovery_ca
    common_name: service-discovery-controller.internal
    extended_key_usage:
    - client_auth
