---
name: performance

addons:
- include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties: {}
  name: bosh-dns

instance_groups:
- azs:
  - z1
  - z2
  instances: 1
  jobs:
  - name: performance-tests
    properties: {}
    release: cf-app-sd
  lifecycle: errand
  name: performance
  networks:
  - name: private
  stemcell: default
  vm_type: m3.medium

- azs:
  - z1
  - z2
  instances: 1

  jobs:
  - name: nats
    properties:
      nats:
        debug: true
        monitor_port: 8222
        password: ((nats_password))
        trace: true
        user: nats
    provides:
      nats:
        as: nats
        shared: true
    release: nats
  name: nats
  networks:
  - name: default
    static_ips: [((nats_ip))]
  stemcell: default
  vm_type: minimal

- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: bosh-dns-adapter
    properties:
      dnshttps:
        client:
          tls:
            ca: ((service_discovery_ca.ca))
            certificate: ((service_discovery_client_tls.certificate))
            private_key: ((service_discovery_client_tls.private_key))
        server:
          ca: ((service_discovery_ca.ca))
    release: cf-app-sd
  - name: service-discovery-controller
    properties:
      dnshttps:
        client:
          ca: ((service_discovery_ca.ca))
        server:
          tls:
            ca: ((service_discovery_ca.ca))
            certificate: ((service_discovery_server_tls.certificate))
            private_key: ((service_discovery_server_tls.private_key))
    release: cf-app-sd
  name: cf-app-sd
  networks:
  - name: default
  stemcell: default
  update:
    max_in_flight: 20
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: small-highmem

releases:
- name: nats
  sha1: bdb04d0d18a71d8b3144e477c43c0f5c72c2eccb
  stemcell:
    os: ubuntu-trusty
    version: latest
  url: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-22-ubuntu-trusty-3468-20171006-173847-874271262.tgz
  version: '22'
- name: bosh-dns
  sha1: daa521930560a5f8543823b2a2984131561362c5
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.0.10
  version: 0.0.10
- name: cf-app-sd
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 5
  serial: false
  update_watch_time: 5000-1200000
variables:
- name: nats_password
  type: password
- name: service_discovery_ca
  type: certificate
  options:
    is_ca: true
    common_name: service-discovery-controller.internal
- name: service_discovery_server_tls
  type: certificate
  options:
    ca: service_discovery_ca
    common_name: service-discovery-controller.internal
    extended_key_usage:
    - server_auth
- name: service_discovery_client_tls
  type: certificate
  options:
    ca: service_discovery_ca
    common_name: service-discovery-controller.internal
    extended_key_usage:
    - client_auth
